### ISSUE TITLE
When are the retired objects actually reclaimed?

### ISSUE THREAD

**Issue by amin-mir** [ibraheemdev/seize#15]
I was reading the crate documentation and tried the TreiberStack implementation from the docs on my machine, but also added Drop trait to `Node<T>` just to get an idea of when the memory of a retired object is actually dropped. According to [docs](https://docs.rs/seize/latest/seize/#2-retired-objects-cannot-be-accessed-by-the-current-thread):

> If no other thread holds a reference to an object it may be reclaimed immediately.

But with the following code, I don't see the `println!` output after the thread pops an element and returns, until later when the whole TreiberStack which contains the Collector is dropped. In other words, `"dropping a node"` only appears after TreiberStack drops.

```Rust
impl<T> Drop for Node<T> {
    fn drop(&mut self) {
        println!("dropping a node");
    }
}
```

and then

```Rust
let stack = Arc::new(TreiberStack::new());

stack.push("1".to_owned());

let stack2 = stack.clone();
thread::spawn(move || {
    let el = stack2.pop().unwrap();
    println!("popped {el}");
}).join().unwrap();
```

I'm looking for some explanation for the memory reclamation part to understand why this is happening.

**Comment by ibraheemdev** [comment]
The node is not being dropped immediately because the default [`batch_size`](https://docs.rs/seize/latest/seize/struct.Collector.html#method.batch_size) is 120, meaning the collector will wait for 120 items to be retired before attempting reclamation. Outside of the batch size, the collector requires more items than the number of active threads per batch. In your example you have 2 active threads, if you set the collector's batch size to 1 and popped 3 items, they would be reclaimed immediately.

**Comment by amin-mir** [comment]
Right, thanks for the explanation!
